language: node_js

sudo: false

node_js:
  - node
  - "8"
  - "8.1"
  - "8.0"
  - "7"
  - "7.2"
  - "7.1"
  - "7.0"
  - "6"
  - "6.9"
  - "6.8"
  - "6.7"
  - "6.6"
  - "6.5"
  - "6.4"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"

branches:
  only:
    - master
